name: build

on:
  push:
  pull_request:

jobs:
  modules:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/gentoo-mipsr5900el:main
    steps:
      - uses: actions/checkout@v3

      - name: Arcive tag
        run: |
          echo "ARCHIVE_TAG=${GITHUB_REF_NAME}-${GITHUB_SHA:0:8}" >> $GITHUB_ENV

      - name: Compile IOP modules
        run: |
          make module CROSS_COMPILE=mipsr5900el-unknown-linux-gnu- V=1
          tar czvf iopmod-modules-${{ env.ARCHIVE_TAG }}.tar.gz module/*.irx

      - name: Publish IOP modules
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: "iopmod-modules-${{ env.ARCHIVE_TAG }}"
          path: iopmod-modules-${{ env.ARCHIVE_TAG }}.tar.gz

  tools:
    strategy:
      matrix:
        arch: [ppc64le, aarch64, x86_64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Arcive tag
        run: |
          echo "ARCHIVE_TAG=${{ matrix.arch }}-${GITHUB_REF_NAME}-${GITHUB_SHA:0:8}" >> $GITHUB_ENV

      - uses: uraimo/run-on-arch-action@v2.2.0
        name: Compile ${{ matrix.arch }} IOP tools
        if: ${{ matrix.arch != 'x86_64' }}
        with:
          arch: ${{ matrix.arch }}
          # Not required, but speeds up builds
          githubToken: ${{ github.token }}
          install: |
            apt-get update -q -y
            apt-get install -q -y git make gcc libc-dev
          run: |
            # Avoid fatal: unsafe repository ('/home/runner/work/iopmod/iopmod' is owned by someone else)
            git config --global --add safe.directory "$PWD"
            make tool LDFLAGS=-static V=1
            tar czvf "iopmod-tools-${{ env.ARCHIVE_TAG }}.tar.gz" tool/iopmod-{info,link,symc}

      - name: Compile x86_64 IOP tools
        if: ${{ matrix.arch == 'x86_64' }}
        run: |
          make tool LDFLAGS=-static V=1
          tar czvf "iopmod-tools-${{ env.ARCHIVE_TAG }}.tar.gz" tool/iopmod-{info,link,symc}

      - name: Publish IOP tools
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: "iopmod-tools-${{ env.ARCHIVE_TAG }}"
          path: iopmod-tools-${{ env.ARCHIVE_TAG }}.tar.gz
